const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const W=require('../khptm-step1.js');
const docs=r=>[r.guidance?.id,r.submission?.id].filter(Boolean);
const move=(r,a,to,detail={})=>W.transfer(r,a,to,{files:docs(r),note:'Chuyển theo nhiệm vụ',...detail});
function guidance(type='Core di động') {const r=W.create('HD-'+type);W.save(r,'tdPM',{types:[type],deadline:W.deadline(2027,[type])});W.prepare(r,'tdPM');return r;}
function submitGuidance(r) {move(r,'tdPM','tdBanLead');W.sign(r,'tdBanLead');move(r,'tdBanLead','tdLeader');}
function receive(type='Core di động') {const r=guidance(type);submitGuidance(r);W.sign(r,'tdLeader');move(r,'tdLeader','tdClerk');W.issue(r,'tdClerk',{number:'HD/2027',date:'2026-10-01',recipients:'Ban KT'});move(r,'tdClerk','ktPM');return r;}
function gnv(type='Core di động') {const p=receive(type),r=W.assignment(p,'ktPM','GNV');W.prepare(r,'ktPM');return {p,r};}
function consult(target='ktPM'){const r=guidance();const f=W.storeConsult(r,'tdPM','request',{unit:'Ban KT',content:'Góp ý định hướng cấu trúc',deadline:'2026-09-25'});move(r,'tdPM',target,{files:[f.id]});return {r,f};}
function response(r){const f=W.storeConsult(r,'ktPM','supply',{content:'Đã góp ý định hướng cấu trúc',period:'2027',issuer:'Ban KT',recipient1:'Tập đoàn'});W.saveResponse(r,'ktPM','Đã góp ý định hướng cấu trúc',[f.id]);return f;}
for(const type of W.types){
 test(`${type}: hướng dẫn TĐ → ký → văn thư ban hành → PM Ban KT → hồ sơ GNV riêng`,()=>{
  const p=receive(type);assert.equal(W.canAssign(p,'ktPM'),true);assert.equal(W.canAssign(p,'tdPM'),false);
  const r=W.assignment(p,'ktPM','GNV-'+type);assert.equal(r.kind,'GNV');assert.equal(r.source.id,p.id);assert.equal(r.data.year,p.data.year);assert.deepEqual(r.data.types,p.data.types);
  W.prepare(r,'ktPM');move(r,'ktPM','ktLead');assert.equal(W.canSign(r,'ktLead'),true);assert.equal(W.primaryDocument(r,'ktLead'),'submission');W.sign(r,'ktLead');move(r,'ktLead','tctLeader');W.sign(r,'tctLeader');
  assert.equal(W.canIssue(r,'tctLeader'),false);move(r,'tctLeader','tctClerk');W.issue(r,'tctClerk',{number:'812/VNPT Net-KT',date:'2026-10-02',recipients:r.data.recipients});W.linkAssignment(p,r);
  assert.equal(p.gnv.number,'812/VNPT Net-KT');assert.equal(p.issue.number,'HD/2027');assert.equal(p.guidance.signer,'tdLeader');assert.equal(r.guidance.signer,'tctLeader');
  move(r,'tctClerk','ktLead',{co:['ktmLead'],view:['ttpPM']});assert.equal(r.receipt.purpose,'IMPLEMENT');assert.equal(W.canSign(r,'ktLead'),false);assert.equal(W.canApprove(r,'ktLead'),false);assert.equal(W.canEdit(r,'ktLead'),false);
  assert.equal(W.primaryDocument(r,'ktLead'),'outgoing');assert.equal(W.primaryDocument(r,'ktmLead'),'outgoing');
  assert.equal(W.canReceive(r,'ktmLead'),true);assert.equal(W.canReceive(r,'ttpPM'),true);assert.deepEqual(W.allowed(r,'tctClerk'),[]);
 });
 test(`${type}: không bắt xin thông tin bước 2 trong bước 1`,()=>{const r=guidance(type);assert.deepEqual(W.allowed(r,'tdPM'),['tdBanLead','ktPM','ktLead']);assert.equal(W.roleKeys(r).includes('ktmPM'),false);assert.throws(()=>move(r,'tdPM','ktmPM'));assert.equal(r.requests.length,0);});
}
test('mốc trước ngày theo SOP riêng cho 4 loại',()=>{assert.equal(W.deadline(2027,['Core di động']),'2026-10-05');assert.equal(W.deadline(2027,['Vô tuyến']),'2026-10-04');assert.equal(W.deadline(2027,['BRCĐ']),'2026-09-30');assert.equal(W.deadline(2027,['CSHT']),'2026-09-30');assert.equal(W.deadline(2027,W.types),'2026-09-30');});
test('không giao nhiệm vụ khi TĐ chưa ký/ban hành/chuyển tới PM',()=>{const r=guidance();assert.throws(()=>W.assignment(r,'tdPM','x'));submitGuidance(r);W.sign(r,'tdLeader');assert.throws(()=>W.assignment(r,'ktPM','x'));move(r,'tdLeader','tdClerk');W.issue(r,'tdClerk',{number:'HD',date:'2026-10-01',recipients:'Ban KT'});assert.equal(W.canAssign(r,'ktPM'),false);assert.throws(()=>W.assignment(r,'ktPM','x'));});
test('đổi Vai trò test không cấp quyền ký / ban hành',()=>{const r=guidance();for(const a of ['tdBanLead','tdLeader','tdClerk','ktLead','tctLeader','tctClerk']){r.viewer=a;assert.equal(W.canEdit(r,a),false);assert.equal(W.canSign(r,a),false);assert.equal(W.canIssue(r,a),false);assert.deepEqual(W.allowed(r,a),[]);assert.throws(()=>W.sign(r,a));assert.throws(()=>W.issue(r,a,{number:'1',date:'2026-10-01'}));}});
test('ký sai người chuyển, nhiệm vụ hoặc phiên bản bị chặn tại handler',()=>{for(const field of ['from','purpose','revision','fingerprint']){const r=guidance();submitGuidance(r);r.receipt[field]=field==='revision'?999:'WRONG';assert.equal(W.canSign(r,'tdLeader'),false);assert.throws(()=>W.sign(r,'tdLeader'));assert.deepEqual(W.allowed(r,'tdLeader'),[]);}});
test('không chuyển văn thư khi chưa ký, không chuyển PM khi chưa ban hành',()=>{const r=guidance();submitGuidance(r);assert.throws(()=>move(r,'tdLeader','tdClerk'));W.sign(r,'tdLeader');move(r,'tdLeader','tdClerk');assert.throws(()=>move(r,'tdClerk','ktPM'));});
test('văn thư TCT không ban hành hướng dẫn TĐ; Văn thư TĐ không ban hành GNV',()=>{const p=guidance();submitGuidance(p);W.sign(p,'tdLeader');move(p,'tdLeader','tdClerk');assert.equal(W.canIssue(p,'tctClerk'),false);const {r}=gnv();move(r,'ktPM','ktLead');W.sign(r,'ktLead');move(r,'ktLead','tctLeader');W.sign(r,'tctLeader');move(r,'tctLeader','tctClerk');assert.equal(W.canIssue(r,'tdClerk'),false);});
test('trả lại hướng dẫn → sửa → trình ký phiên bản mới',()=>{const r=guidance();submitGuidance(r);assert.throws(()=>move(r,'tdLeader','tdPM',{note:''}));move(r,'tdLeader','tdPM',{note:'Bổ sung định hướng'});W.save(r,'tdPM',{content:'Nội dung hướng dẫn đã bổ sung'});W.prepare(r,'tdPM');submitGuidance(r);W.sign(r,'tdLeader');assert.equal(r.guidance.revision,r.revision);});
test('TCT trả LĐ Ban KT chỉ phân công PM sửa, không tự cấp quyền ký',()=>{const {r}=gnv();move(r,'ktPM','ktLead');W.sign(r,'ktLead');move(r,'ktLead','tctLeader');move(r,'tctLeader','ktLead',{note:'Bổ sung phân công'});assert.equal(W.canSign(r,'ktLead'),false);assert.deepEqual(W.allowed(r,'ktLead'),['ktPM']);move(r,'ktLead','ktPM',{note:'Hoàn thiện theo ý kiến TCT'});W.save(r,'ktPM',{content:'Phân công đã bổ sung'});W.prepare(r,'ktPM');move(r,'ktPM','ktLead');assert.equal(W.canSign(r,'ktLead'),true);assert.equal(r.guidance.signed,false);});
test('TCT trả thẳng PM phải đi lại vòng LĐ Ban KT → LĐTCT',()=>{const {r}=gnv();move(r,'ktPM','ktLead');W.sign(r,'ktLead');move(r,'ktLead','tctLeader');move(r,'tctLeader','ktPM',{note:'Sửa nội dung'});assert.equal(r.submission.signed,false);assert.equal(r.guidance.signed,false);assert.deepEqual(W.allowed(r,'ktPM'),['ktLead']);assert.throws(()=>move(r,'ktPM','tctLeader'));});
test('ký Tờ trình không tự ký VB GNV và không làm thay văn thư',()=>{const {r}=gnv();move(r,'ktPM','ktLead');W.sign(r,'ktLead');assert.equal(r.submission.signed,true);assert.equal(r.guidance.signed,false);assert.equal(r.issue.issued,undefined);assert.throws(()=>W.issue(r,'ktLead',{}));});
test('ban hành chỉ một lần, số ngày nơi nhận bắt buộc',()=>{const r=guidance();submitGuidance(r);W.sign(r,'tdLeader');move(r,'tdLeader','tdClerk');assert.throws(()=>W.issue(r,'tdClerk',{number:'',date:'2026-09-30',recipients:'Ban KT'}));assert.throws(()=>W.issue(r,'tdClerk',{number:'HD',date:'bad',recipients:'Ban KT'}));W.issue(r,'tdClerk',{number:'HD',date:'2026-09-30',recipients:'Ban KT'});assert.throws(()=>W.issue(r,'tdClerk',{number:'HD2',date:'2026-09-30',recipients:'Ban KT'}));});
test('tài liệu đúng phiên bản và đủ bộ khi chuyển',()=>{const {r}=gnv();assert.throws(()=>move(r,'ktPM','ktLead',{files:[r.guidance.id]}));assert.equal(r.owner,'ktPM');move(r,'ktPM','ktLead');r.data.content='Đã sửa không đúng quy trình';assert.equal(W.canSign(r,'ktLead'),false);assert.deepEqual(W.allowed(r,'ktLead'),[]);});
test('ghi nhận VB TĐ ngoài hệ thống không ký hoặc ban hành lại',()=>{const r=W.create('EXT','EXTERNAL');assert.throws(()=>W.recordExternal(r,'ktPM',{number:'HD',date:'2026-09-30'},{}));const f={name:'HD-da-ky.pdf',url:'blob:original',bytes:[1,2,3]};W.recordExternal(r,'ktPM',{number:'HD',date:'2026-09-30',confirmed:true},f);assert.equal(r.guidance.external.url,'blob:original');assert.deepEqual(r.guidance.external.bytes,[1,2,3]);assert.equal(W.canAssign(r,'ktPM'),true);assert.equal(W.canSign(r,'tdLeader'),false);assert.equal(W.canIssue(r,'tdClerk'),false);assert.throws(()=>W.recordExternal(r,'ktPM',{number:'2',date:'2026-10-01',confirmed:true},f));});
test('hướng dẫn đã ban hành khóa nghiệp vụ; chỉ một hồ sơ GNV liên kết',()=>{const p=receive();assert.throws(()=>W.save(p,'ktPM',{content:'Sửa'}));const r=W.assignment(p,'ktPM','GNV');assert.deepEqual(W.assignment(p,'ktPM','GNV2'),{existingId:'GNV'});assert.equal(p.gnv.id,r.id);});
test('không liên kết nhầm hồ sơ / phiên bản nguồn',()=>{const {p,r}=gnv();const p2=receive('CSHT');assert.throws(()=>W.linkAssignment(p2,r));p.issue.number='HD đã đổi';assert.throws(()=>W.linkAssignment(p,r));});
test('GNV phải dùng đúng năm và hướng dẫn nguồn',()=>{const {r}=gnv();W.save(r,'ktPM',{year:'2028'});assert.throws(()=>W.prepare(r,'ktPM'));const {r:b}=gnv();b.source.data.content='Sai nguồn';assert.throws(()=>W.prepare(b,'ktPM'));});
test('nhánh xin ý kiến Ban KT là tùy chọn; không ép qua LĐ',()=>{const {r}=consult();const f=response(r);move(r,'ktPM','tdPM',{files:[f.id]});assert.equal(r.owner,'tdPM');assert.equal(r.receipt.from,'ktPM');assert.equal(W.canEdit(r,'tdPM'),true);assert.equal(r.requests[0].approvedRevision,0);W.prepare(r,'tdPM');submitGuidance(r);assert.equal(W.canSign(r,'tdLeader'),true);});
test('LĐ Ban KT nhận yêu cầu TĐ chỉ phân công; nhận phản hồi PM của mình mới duyệt',()=>{const {r}=consult('ktLead');assert.equal(W.canApprove(r,'ktLead'),false);assert.equal(W.canSign(r,'ktLead'),false);move(r,'ktLead','ktPM');const f=response(r);move(r,'ktPM','ktLead',{files:[f.id]});assert.equal(W.canApprove(r,'ktLead'),true);assert.throws(()=>move(r,'ktLead','tdPM',{files:[f.id]}));W.approve(r,'ktLead');move(r,'ktLead','tdPM',{files:[f.id]});assert.equal(W.canEdit(r,'tdPM'),true);assert.equal(r.receipt.from,'ktLead');});
test('phản hồi bị trả → phiên bản mới phải duyệt lại',()=>{const {r}=consult();const f=response(r);move(r,'ktPM','ktLead',{files:[f.id]});W.approve(r,'ktLead');assert.throws(()=>move(r,'ktLead','ktPM',{note:''}));move(r,'ktLead','ktPM',{note:'Bổ sung'});assert.equal(r.requests[0].approvedRevision,0);const f2=response(r);move(r,'ktPM','ktLead',{files:[f2.id]});assert.equal(W.canApprove(r,'ktLead'),true);assert.throws(()=>move(r,'ktLead','tdPM',{files:[f2.id]}));});
test('sai nguồn / phiên bản phản hồi không cấp Duyệt',()=>{for(const change of ['from','responseRevision']){const {r}=consult();const f=response(r);move(r,'ktPM','ktLead',{files:[f.id]});r.requests[0].receipt[change]=change==='from'?'tdPM':999;assert.equal(W.canApprove(r,'ktLead'),false);assert.throws(()=>W.approve(r,'ktLead'));}});
test('nhánh xin ý kiến đã chọn phải hoàn tất trước khi ký',()=>{const {r}=consult();r.viewer='tdPM';assert.throws(()=>move(r,'tdPM','tdBanLead'));assert.equal(r.owner,'tdPM');});
test('không gửi Ban KTM / NetX dưới dạng nhiệm vụ bước 1',()=>{const r=guidance();assert.throws(()=>W.storeConsult(r,'tdPM','request',{unit:'Ban KTM',content:'Xin',deadline:'2026-09-25'}));assert.throws(()=>move(r,'tdPM','netPM'));});
test('phải chọn VB yêu cầu, không lấy yêu cầu hồ sơ khác',()=>{const r=guidance();assert.throws(()=>move(r,'tdPM','ktPM',{files:[]}));assert.equal(r.requests.length,0);const {r:a}=consult();assert.throws(()=>W.saveResponse(a,'ktPM','Ý kiến',['file-from-other-record']));});
test('không trình ký nếu chọn thiếu phản hồi hoặc sai người xử lý',()=>{const {r}=consult();const f=response(r);assert.throws(()=>move(r,'ktPM','tdPM',{files:[]}));assert.throws(()=>W.saveResponse(r,'tdLeader','Sai',[]));move(r,'ktPM','tdPM',{files:[f.id]});assert.throws(()=>W.saveResponse(r,'ktPM','Sai',[]));});
test('upload văn bản đã ký hợp lệ và chặn file sai trước khi đổi chữ ký',()=>{const r=guidance();submitGuidance(r);assert.throws(()=>W.sign(r,'tdLeader',{name:'file.exe'}));assert.equal(r.guidance.signed,false);W.sign(r,'tdLeader',{name:'HD-da-ky.pdf',url:'blob:signed'});assert.equal(r.guidance.signatureSource,'external');assert.equal(r.guidance.external.url,'blob:signed');move(r,'tdLeader','tdClerk');assert.equal(W.canIssue(r,'tdClerk'),true);});
test('sửa source receipt không cấp nút GNV',()=>{for(const field of ['from','files','sourceFingerprint']){const p=receive();p.receipt[field]=field==='files'?[]:'wrong';assert.equal(W.canAssign(p,'ktPM'),false);assert.throws(()=>W.assignment(p,'ktPM','GNV'));}});
test('GNV chỉ phát hành cho đơn vị đã ghi trong nội dung phân công',()=>{const {r}=gnv();W.save(r,'ktPM',{recipients:'Ban KT; Ban KTM'});W.prepare(r,'ktPM');move(r,'ktPM','ktLead');W.sign(r,'ktLead');move(r,'ktLead','tctLeader');W.sign(r,'tctLeader');move(r,'tctLeader','tctClerk');W.issue(r,'tctClerk',{number:'GNV',date:'2026-10-02',recipients:r.data.recipients});assert.deepEqual(W.allowed(r,'tctClerk'),['ktLead','ktPM','ktmLead','ktmPM']);assert.throws(()=>move(r,'tctClerk','ttpPM'));});
test('model bước 1 không đọc hoặc ghi state của chức năng khác',()=>{const text=fs.readFileSync(require.resolve('../khptm-step1.js'),'utf8').split('(function () {')[0];assert.equal(/khptm2Step|khptm2Role|khptm2Requests|khptmPairStates|KHStep5\./.test(text),false);});
test('PM TĐ lập hai tài liệu và không được bỏ qua LĐ Ban chủ trì TĐ',()=>{const r=guidance();assert.equal(r.submission.kind,'submission');assert.equal(r.guidance.kind,'guidance');assert.deepEqual(W.prepare(r,'tdPM').map(f=>f.id),docs(r));assert.throws(()=>move(r,'tdPM','tdLeader'));assert.throws(()=>move(r,'tdPM','tdBanLead',{files:[r.guidance.id]}));assert.equal(r.owner,'tdPM');move(r,'tdPM','tdBanLead');assert.equal(W.canSign(r,'tdBanLead'),true);assert.equal(W.canSign(r,'tdLeader'),false);assert.throws(()=>move(r,'tdBanLead','tdLeader'));});
test('LĐ Ban chủ trì TĐ ký riêng Tờ trình; LĐ TĐ ký riêng dự thảo hướng dẫn',()=>{const r=guidance();move(r,'tdPM','tdBanLead');W.sign(r,'tdBanLead');assert.equal(r.submission.signer,'tdBanLead');assert.equal(r.guidance.signed,false);assert.deepEqual(W.allowed(r,'tdBanLead'),['tdLeader']);move(r,'tdBanLead','tdLeader');assert.equal(W.canSign(r,'tdLeader'),true);W.sign(r,'tdLeader');assert.equal(r.guidance.signer,'tdLeader');assert.equal(r.submission.signer,'tdBanLead');assert.equal(r.issue.issued,undefined);assert.equal(W.canAssign(r,'ktPM'),false);});
test('thiếu chữ ký Tờ trình hoặc sai người ký không cấp quyền LĐ TĐ / Văn thư',()=>{for(const field of ['signed','signer','revision','fingerprint']){const r=guidance();submitGuidance(r);r.submission[field]=field==='signed'?false:field==='revision'?999:'wrong';assert.equal(W.canSign(r,'tdLeader'),false);assert.deepEqual(W.allowed(r,'tdLeader'),[]);assert.throws(()=>W.sign(r,'tdLeader'));}
 const r=guidance();submitGuidance(r);W.sign(r,'tdLeader');move(r,'tdLeader','tdClerk');r.submission.signed=false;assert.equal(W.canIssue(r,'tdClerk'),false);assert.throws(()=>W.takeNumber(r,'tdClerk'));assert.throws(()=>W.issue(r,'tdClerk',{number:'HD',date:'2026-10-01',recipients:'Ban KT'}));});
test('LĐ TĐ nhận sai nguồn hoặc mục đích không được ký dù có file đã ký',()=>{for(const field of ['from','purpose','files']){const r=guidance();submitGuidance(r);r.receipt[field]=field==='files'?[r.guidance.id]:field==='from'?'tdPM':'ASSIGN';assert.equal(W.canSign(r,'tdLeader'),false);assert.throws(()=>W.sign(r,'tdLeader'));assert.deepEqual(W.allowed(r,'tdLeader'),[]);}});
test('LĐ TĐ trả LĐ Ban chủ trì TĐ chỉ chuyển PM sửa; phải trình lại đủ vòng',()=>{const r=guidance();submitGuidance(r);assert.throws(()=>move(r,'tdLeader','tdBanLead',{note:''}));move(r,'tdLeader','tdBanLead',{note:'Bổ sung nguyên tắc'});assert.equal(r.receipt.purpose,'ASSIGN_TD_REVISE');assert.equal(W.canSign(r,'tdBanLead'),false);assert.equal(W.canEdit(r,'tdBanLead'),false);assert.deepEqual(W.allowed(r,'tdBanLead'),['tdPM']);assert.throws(()=>move(r,'tdBanLead','tdLeader'));move(r,'tdBanLead','tdPM',{note:'Hoàn thiện theo ý kiến LĐ TĐ'});W.save(r,'tdPM',{principles:'Nguyên tắc đã bổ sung'});W.prepare(r,'tdPM');assert.equal(r.submission.signed,false);assert.equal(r.guidance.signed,false);assert.throws(()=>move(r,'tdPM','tdLeader'));submitGuidance(r);assert.equal(W.canSign(r,'tdLeader'),true);});
test('LĐ Ban chủ trì TĐ trả PM sửa Tờ trình và hướng dẫn cùng phiên bản',()=>{const r=guidance();move(r,'tdPM','tdBanLead');move(r,'tdBanLead','tdPM',{note:'Hoàn thiện Tờ trình'});const prior=r.revision;W.save(r,'tdPM',{content:'Hướng dẫn đã bổ sung'});W.prepare(r,'tdPM');assert.equal(r.revision,prior+1);assert.equal(r.submission.revision,r.guidance.revision);assert.equal(r.submission.signed,false);move(r,'tdPM','tdBanLead');assert.equal(W.canSign(r,'tdBanLead'),true);});
test('Lấy số chỉ cho Văn thư đúng nhiệm vụ sau khi có đủ chữ ký',()=>{const r=guidance();for(const a of W.roleKeys(r))assert.throws(()=>W.takeNumber(r,a,[r]));submitGuidance(r);W.sign(r,'tdLeader');assert.throws(()=>W.takeNumber(r,'tdClerk',[r]));move(r,'tdLeader','tdClerk');assert.throws(()=>W.takeNumber(r,'tctClerk',[r]));const number=W.takeNumber(r,'tdClerk',[r]);assert.equal(number,'1001');assert.equal(W.takeNumber(r,'tdClerk',[r]),number);W.issue(r,'tdClerk',{number:number+'/VNPT-CN',serial:number,date:'2026-10-01',recipients:'Ban KT'});assert.throws(()=>W.takeNumber(r,'tdClerk',[r]));});
test('Lấy số liên tiếp trong cùng cấp, tách cấp TĐ/TCT và giữ số đã nhập',()=>{const td=guidance();submitGuidance(td);W.sign(td,'tdLeader');move(td,'tdLeader','tdClerk');W.takeNumber(td,'tdClerk',[td]);const td2=guidance('CSHT');submitGuidance(td2);W.sign(td2,'tdLeader');move(td2,'tdLeader','tdClerk');assert.equal(W.takeNumber(td2,'tdClerk',[td,td2]),'1002');const {r}=gnv();move(r,'ktPM','ktLead');W.sign(r,'ktLead');move(r,'ktLead','tctLeader');W.sign(r,'tctLeader');move(r,'tctLeader','tctClerk');assert.equal(W.takeNumber(r,'tctClerk',[td,td2,r]),'813');r.issueDraft.number='820';assert.equal(W.takeNumber(r,'tctClerk',[td,td2,r]),'820');});
test('nhập hướng dẫn đã ban hành ngoài hệ thống không sinh Tờ trình TĐ giả',()=>{const r=W.create('IMPORT','EXTERNAL');W.recordExternal(r,'ktPM',{number:'HD',date:'2026-09-30',confirmed:true},{name:'HD.pdf',bytes:[1,2,3],url:'blob:original'});assert.equal(r.submission,null);assert.equal(W.canAssign(r,'ktPM'),true);assert.equal(W.canSign(r,'tdBanLead'),false);assert.throws(()=>W.takeNumber(r,'ktPM',[r]));});
